/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jframe.proj;

import javax.swing.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static final JFrame frame = new JFrame();
    public static final String TITLE = "game alpha 0.02";

    public static void main(String[] args) {

        //init a display of a certain size and display it
        Display game = new Display();
        frame.add(game);
        frame.pack();
        frame.setTitle(TITLE);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setSize(800, 800);
        frame.setResizable(false);
        frame.setVisible(true);
        System.out.println("running JFrame init in Display.java...");

        game.start();
    }
}
